export const LANDING = "/";
export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const HOME = '/postlistings';
export const ACCOUNT = '/account';
export const CREATE_POST = '/createpost';
export const EDIT_PROFILE='/user/edituserprofile';
export const USER_PROFILE='/user/userprofile/:uid';
export const POST_LISTINGS = '/postlistings';
export const DETAILED_POST = '/post/:uid'
export const ERROR = '/error-pages/error-500';